---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

df <- read.csv("../Day 7/input.csv")

df$child2C[as.character(df$child2C) == " "] <- NA
df$child3C[as.character(df$child3C) == " "] <- NA
df$child4C[as.character(df$child4C) == " "] <- NA

df
```

```{r}
shinygoldDF <- df %>% filter(as.character(parent) == "shiny gold" | as.character(child1C) == "shiny gold" | as.character(child2C) == "shiny gold" | 
                               as.character(child3C) == "shiny gold" | as.character(child4C) == "shiny gold")

oldRows <- 0

while(oldRows != nrow(shinygoldDF)) {
  oldRows <- nrow(shinygoldDF)
  level <- unlist(shinygoldDF$parent)
  shinygoldDF <- df %>% filter(as.character(parent) %in% level | as.character(child1C) %in% level | as.character(child2C)%in% level | 
                                 as.character(child3C) %in% level | as.character(child4C) %in% level)
}
shinygoldDF
```

```{r}
shinygoldVEC <- shinygoldDF %>% 
  filter(as.character(parent) == "shiny gold") %>%
  select(seq(3, 9, by=2)) %>%
  unlist() %>%
  as.vector()

runningTotal = 1

for(i in shinygoldVEC) {
  shinygoldDF <- df %>% filter(as.character(parent) == i | as.character(child1C) == i | as.character(child2C) == i | 
                               as.character(child3C) == i | as.character(child4C) == i)

  oldRows <- 0

  while(oldRows != nrow(shinygoldDF)) {
    oldRows <- nrow(shinygoldDF)
    level <- unlist(shinygoldDF$parent)
    shinygoldDF <- df %>% filter(as.character(parent) %in% level | as.character(child1C) %in% level | as.character(child2C)%in% level | 
                                 as.character(child3C) %in% level | as.character(child4C) %in% level)
  }
  runningTotal <- runningTotal * nrow(shinygoldDF)
}
runningTotal
```

